on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Review it
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Let Linus Torvalds review this PR
        uses: ./ # Uses an action in the root directory
        env:
          GITHUB_TOKEN: ${{ github.token }}
